# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapi',
            name='node_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
