# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_auto_20180923_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapi',
            name='site_admin',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='user_type',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
