# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20180923_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapi',
            name='bio',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='blog',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='company',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='hireable',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='githubapi',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
