# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_githubapi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapi',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
