# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_githubapi_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubapi',
            name='gravatar_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='githubapi',
            name='node_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
