# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_auto_20180923_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapi',
            name='added_on',
            field=models.DateTimeField(null=True),
        ),
    ]
